
package webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BoardGameOrderWSService", targetNamespace = "http://webservice.tienda.proyecto.ws/", wsdlLocation = "http://localhost:8080/WS.Proyecto.Tienda/soapws/boardgameorder?wsdl")
public class BoardGameOrderWSService
    extends Service
{

    private final static URL BOARDGAMEORDERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOARDGAMEORDERWSSERVICE_EXCEPTION;
    private final static QName BOARDGAMEORDERWSSERVICE_QNAME = new QName("http://webservice.tienda.proyecto.ws/", "BoardGameOrderWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS.Proyecto.Tienda/soapws/boardgameorder?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOARDGAMEORDERWSSERVICE_WSDL_LOCATION = url;
        BOARDGAMEORDERWSSERVICE_EXCEPTION = e;
    }

    public BoardGameOrderWSService() {
        super(__getWsdlLocation(), BOARDGAMEORDERWSSERVICE_QNAME);
    }

    public BoardGameOrderWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOARDGAMEORDERWSSERVICE_QNAME, features);
    }

    public BoardGameOrderWSService(URL wsdlLocation) {
        super(wsdlLocation, BOARDGAMEORDERWSSERVICE_QNAME);
    }

    public BoardGameOrderWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOARDGAMEORDERWSSERVICE_QNAME, features);
    }

    public BoardGameOrderWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoardGameOrderWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBoardGameOrderWS
     */
    @WebEndpoint(name = "BoardGameOrderWSPort")
    public IBoardGameOrderWS getBoardGameOrderWSPort() {
        return super.getPort(new QName("http://webservice.tienda.proyecto.ws/", "BoardGameOrderWSPort"), IBoardGameOrderWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBoardGameOrderWS
     */
    @WebEndpoint(name = "BoardGameOrderWSPort")
    public IBoardGameOrderWS getBoardGameOrderWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.tienda.proyecto.ws/", "BoardGameOrderWSPort"), IBoardGameOrderWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOARDGAMEORDERWSSERVICE_EXCEPTION!= null) {
            throw BOARDGAMEORDERWSSERVICE_EXCEPTION;
        }
        return BOARDGAMEORDERWSSERVICE_WSDL_LOCATION;
    }

}
