
package webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BoardGameWSService", targetNamespace = "http://webservice.tienda.proyecto.ws/", wsdlLocation = "http://localhost:8080/WS.Proyecto.Tienda/soapws/boardgame?wsdl")
public class BoardGameWSService
    extends Service
{

    private final static URL BOARDGAMEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOARDGAMEWSSERVICE_EXCEPTION;
    private final static QName BOARDGAMEWSSERVICE_QNAME = new QName("http://webservice.tienda.proyecto.ws/", "BoardGameWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS.Proyecto.Tienda/soapws/boardgame?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOARDGAMEWSSERVICE_WSDL_LOCATION = url;
        BOARDGAMEWSSERVICE_EXCEPTION = e;
    }

    public BoardGameWSService() {
        super(__getWsdlLocation(), BOARDGAMEWSSERVICE_QNAME);
    }

    public BoardGameWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOARDGAMEWSSERVICE_QNAME, features);
    }

    public BoardGameWSService(URL wsdlLocation) {
        super(wsdlLocation, BOARDGAMEWSSERVICE_QNAME);
    }

    public BoardGameWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOARDGAMEWSSERVICE_QNAME, features);
    }

    public BoardGameWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoardGameWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBoardGameWS
     */
    @WebEndpoint(name = "BoardGameWSPort")
    public IBoardGameWS getBoardGameWSPort() {
        return super.getPort(new QName("http://webservice.tienda.proyecto.ws/", "BoardGameWSPort"), IBoardGameWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBoardGameWS
     */
    @WebEndpoint(name = "BoardGameWSPort")
    public IBoardGameWS getBoardGameWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.tienda.proyecto.ws/", "BoardGameWSPort"), IBoardGameWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOARDGAMEWSSERVICE_EXCEPTION!= null) {
            throw BOARDGAMEWSSERVICE_EXCEPTION;
        }
        return BOARDGAMEWSSERVICE_WSDL_LOCATION;
    }

}
