
package webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBoardGameOrderWS", targetNamespace = "http://webservice.tienda.proyecto.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBoardGameOrderWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBoardGameOrder", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.CreateBoardGameOrder")
    @ResponseWrapper(localName = "createBoardGameOrderResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.CreateBoardGameOrderResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IBoardGameOrderWS/createBoardGameOrderRequest", output = "http://webservice.tienda.proyecto.ws/IBoardGameOrderWS/createBoardGameOrderResponse")
    public boolean createBoardGameOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        BoardGameOrder arg0);

}
