
package webService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBoardGameWS", targetNamespace = "http://webservice.tienda.proyecto.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBoardGameWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.UpdateResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IBoardGameWS/updateRequest", output = "http://webservice.tienda.proyecto.ws/IBoardGameWS/updateResponse")
    public boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        BoardGame arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.DeleteResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IBoardGameWS/deleteRequest", output = "http://webservice.tienda.proyecto.ws/IBoardGameWS/deleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webService.BoardGame
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.ReadResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IBoardGameWS/readRequest", output = "http://webservice.tienda.proyecto.ws/IBoardGameWS/readResponse")
    public BoardGame read(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.CreateResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IBoardGameWS/createRequest", output = "http://webservice.tienda.proyecto.ws/IBoardGameWS/createResponse")
    public boolean create(
        @WebParam(name = "arg0", targetNamespace = "")
        BoardGame arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webService.BoardGame>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.FindByNameResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IBoardGameWS/findByNameRequest", output = "http://webservice.tienda.proyecto.ws/IBoardGameWS/findByNameResponse")
    public List<BoardGame> findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webService.BoardGame>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAll", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.ReadAll")
    @ResponseWrapper(localName = "readAllResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.ReadAllResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IBoardGameWS/readAllRequest", output = "http://webservice.tienda.proyecto.ws/IBoardGameWS/readAllResponse")
    public List<BoardGame> readAll();

}
