
package webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrderWS", targetNamespace = "http://webservice.tienda.proyecto.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOrderWS {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderId", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.OrderId")
    @ResponseWrapper(localName = "orderIdResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.OrderIdResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IOrderWS/orderIdRequest", output = "http://webservice.tienda.proyecto.ws/IOrderWS/orderIdResponse")
    public int orderId();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.CreateOrderResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IOrderWS/createOrderRequest", output = "http://webservice.tienda.proyecto.ws/IOrderWS/createOrderResponse")
    public boolean createOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
