
package webService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserWS", targetNamespace = "http://webservice.tienda.proyecto.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.CreateUserResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IUserWS/createUserRequest", output = "http://webservice.tienda.proyecto.ws/IUserWS/createUserResponse")
    public boolean createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<webService.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUsernamePassword", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.FindByUsernamePassword")
    @ResponseWrapper(localName = "findByUsernamePasswordResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.FindByUsernamePasswordResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IUserWS/findByUsernamePasswordRequest", output = "http://webservice.tienda.proyecto.ws/IUserWS/findByUsernamePasswordResponse")
    public List<User> findByUsernamePassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns webService.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readUser", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.ReadUser")
    @ResponseWrapper(localName = "readUserResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.ReadUserResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IUserWS/readUserRequest", output = "http://webservice.tienda.proyecto.ws/IUserWS/readUserResponse")
    public User readUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.DeleteUserResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IUserWS/deleteUserRequest", output = "http://webservice.tienda.proyecto.ws/IUserWS/deleteUserResponse")
    public boolean deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.UpdateUserResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IUserWS/updateUserRequest", output = "http://webservice.tienda.proyecto.ws/IUserWS/updateUserResponse")
    public boolean updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webService.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAllUsers", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.ReadAllUsers")
    @ResponseWrapper(localName = "readAllUsersResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.ReadAllUsersResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IUserWS/readAllUsersRequest", output = "http://webservice.tienda.proyecto.ws/IUserWS/readAllUsersResponse")
    public List<User> readAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webService.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUsername", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.FindByUsername")
    @ResponseWrapper(localName = "findByUsernameResponse", targetNamespace = "http://webservice.tienda.proyecto.ws/", className = "webService.FindByUsernameResponse")
    @Action(input = "http://webservice.tienda.proyecto.ws/IUserWS/findByUsernameRequest", output = "http://webservice.tienda.proyecto.ws/IUserWS/findByUsernameResponse")
    public List<User> findByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
